### ISSUE TITLE
DD does not mention FEF (?)

### ISSUE THREAD

**Issue by tofr** [KendrickLiang/Softdev_Project02#1]

**Comment by weiwenzhou** [comment]
We are using foundation.

**Comment by tofr** [comment]
which frontend framework you are using (Bootstrap or Foundation) and why

Topher Mykolyk
Stuyvesant CS
+

**Comment by weiwenzhou** [comment]
We are using Foundation. We chose Foundation over Bootstrap primarily because foundation’s grid layout is more flexible and simplistic than bootstrap’s. While bootstrap has more detailed documentation, we believe this aspect would be more harmful to us than beneficial. Since we are planning to use a lot of graphics in order to create our game, we would like to have a simple and robust FEF that gets the job done without over the top styling, but also be able to customized with a unique feel.
